### ISSUE TITLE
Password synchronization delay

### ISSUE THREAD

**Issue by Sly555** [strimzi/kafka-access-operator#19] opened 2023-02-01 13:32 UTC
Hi

We use kafkaaccess with scran-sh-512 kafkausers. The first time a crd is added for a project the secret is created in this project.

When the kafkauser password changes in kafka, kafakaccess does not change the password of the secret created in the project for a few hours. To test it : in my kafka project I delete the secret my kafka entity operator create a new one.

For the project with a kafkaaccess crd : If I delete the secret in this project kafkaaccess recreate it with the new value. But if I do nothing I have to wait for approx 10 hours before the secret is updated.

In the logs I've see : 2023-01-23 10:44:09 DEBUG EventProcessor:284 - ReScheduling event for resource: ResourceID{name='connexion-kafka', namespace='-----} with delay: 36000000

Maybe it is this long delay who cause this.

What we need : When the kafkauser secret change the secret assosiate with the crd should change too in a small delay.

Thanks

**Comment by katheris** [comment] 2023-08-01 16:43
Hi @Sly555, I've managed to replicate the issue and found the cause, we are missing an event source for the secrets managed by the Strimzi User Operator. I'm working on a fix and will hopefully get a pull request raised and merged soon.

**Closed** 2023-08-07 09:52 UTC
